// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Agenda.proto

public final class AgendaOuterClass {
  private AgendaOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ContatoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Contato)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string nome = 1;</code>
     */
    boolean hasNome();
    /**
     * <code>required string nome = 1;</code>
     */
    java.lang.String getNome();
    /**
     * <code>required string nome = 1;</code>
     */
    com.google.protobuf.ByteString
        getNomeBytes();

    /**
     * <code>required string telefone = 2;</code>
     */
    boolean hasTelefone();
    /**
     * <code>required string telefone = 2;</code>
     */
    java.lang.String getTelefone();
    /**
     * <code>required string telefone = 2;</code>
     */
    com.google.protobuf.ByteString
        getTelefoneBytes();
  }
  /**
   * Protobuf type {@code Contato}
   */
  public  static final class Contato extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Contato)
      ContatoOrBuilder {
    // Use Contato.newBuilder() to construct.
    private Contato(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Contato() {
      nome_ = "";
      telefone_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Contato(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              nome_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              telefone_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return AgendaOuterClass.internal_static_Contato_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return AgendaOuterClass.internal_static_Contato_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              AgendaOuterClass.Contato.class, AgendaOuterClass.Contato.Builder.class);
    }

    private int bitField0_;
    public static final int NOME_FIELD_NUMBER = 1;
    private volatile java.lang.Object nome_;
    /**
     * <code>required string nome = 1;</code>
     */
    public boolean hasNome() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string nome = 1;</code>
     */
    public java.lang.String getNome() {
      java.lang.Object ref = nome_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          nome_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string nome = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNomeBytes() {
      java.lang.Object ref = nome_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nome_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TELEFONE_FIELD_NUMBER = 2;
    private volatile java.lang.Object telefone_;
    /**
     * <code>required string telefone = 2;</code>
     */
    public boolean hasTelefone() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string telefone = 2;</code>
     */
    public java.lang.String getTelefone() {
      java.lang.Object ref = telefone_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          telefone_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string telefone = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTelefoneBytes() {
      java.lang.Object ref = telefone_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        telefone_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasNome()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTelefone()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, nome_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, telefone_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, nome_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, telefone_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof AgendaOuterClass.Contato)) {
        return super.equals(obj);
      }
      AgendaOuterClass.Contato other = (AgendaOuterClass.Contato) obj;

      boolean result = true;
      result = result && (hasNome() == other.hasNome());
      if (hasNome()) {
        result = result && getNome()
            .equals(other.getNome());
      }
      result = result && (hasTelefone() == other.hasTelefone());
      if (hasTelefone()) {
        result = result && getTelefone()
            .equals(other.getTelefone());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasNome()) {
        hash = (37 * hash) + NOME_FIELD_NUMBER;
        hash = (53 * hash) + getNome().hashCode();
      }
      if (hasTelefone()) {
        hash = (37 * hash) + TELEFONE_FIELD_NUMBER;
        hash = (53 * hash) + getTelefone().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static AgendaOuterClass.Contato parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AgendaOuterClass.Contato parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AgendaOuterClass.Contato parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AgendaOuterClass.Contato parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AgendaOuterClass.Contato parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AgendaOuterClass.Contato parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static AgendaOuterClass.Contato parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static AgendaOuterClass.Contato parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static AgendaOuterClass.Contato parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AgendaOuterClass.Contato parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(AgendaOuterClass.Contato prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Contato}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Contato)
        AgendaOuterClass.ContatoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return AgendaOuterClass.internal_static_Contato_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return AgendaOuterClass.internal_static_Contato_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                AgendaOuterClass.Contato.class, AgendaOuterClass.Contato.Builder.class);
      }

      // Construct using AgendaOuterClass.Contato.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        nome_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        telefone_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return AgendaOuterClass.internal_static_Contato_descriptor;
      }

      public AgendaOuterClass.Contato getDefaultInstanceForType() {
        return AgendaOuterClass.Contato.getDefaultInstance();
      }

      public AgendaOuterClass.Contato build() {
        AgendaOuterClass.Contato result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public AgendaOuterClass.Contato buildPartial() {
        AgendaOuterClass.Contato result = new AgendaOuterClass.Contato(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.nome_ = nome_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.telefone_ = telefone_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof AgendaOuterClass.Contato) {
          return mergeFrom((AgendaOuterClass.Contato)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(AgendaOuterClass.Contato other) {
        if (other == AgendaOuterClass.Contato.getDefaultInstance()) return this;
        if (other.hasNome()) {
          bitField0_ |= 0x00000001;
          nome_ = other.nome_;
          onChanged();
        }
        if (other.hasTelefone()) {
          bitField0_ |= 0x00000002;
          telefone_ = other.telefone_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasNome()) {
          return false;
        }
        if (!hasTelefone()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        AgendaOuterClass.Contato parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (AgendaOuterClass.Contato) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object nome_ = "";
      /**
       * <code>required string nome = 1;</code>
       */
      public boolean hasNome() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string nome = 1;</code>
       */
      public java.lang.String getNome() {
        java.lang.Object ref = nome_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            nome_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string nome = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNomeBytes() {
        java.lang.Object ref = nome_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nome_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string nome = 1;</code>
       */
      public Builder setNome(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        nome_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string nome = 1;</code>
       */
      public Builder clearNome() {
        bitField0_ = (bitField0_ & ~0x00000001);
        nome_ = getDefaultInstance().getNome();
        onChanged();
        return this;
      }
      /**
       * <code>required string nome = 1;</code>
       */
      public Builder setNomeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        nome_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object telefone_ = "";
      /**
       * <code>required string telefone = 2;</code>
       */
      public boolean hasTelefone() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string telefone = 2;</code>
       */
      public java.lang.String getTelefone() {
        java.lang.Object ref = telefone_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            telefone_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string telefone = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTelefoneBytes() {
        java.lang.Object ref = telefone_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          telefone_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string telefone = 2;</code>
       */
      public Builder setTelefone(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        telefone_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string telefone = 2;</code>
       */
      public Builder clearTelefone() {
        bitField0_ = (bitField0_ & ~0x00000002);
        telefone_ = getDefaultInstance().getTelefone();
        onChanged();
        return this;
      }
      /**
       * <code>required string telefone = 2;</code>
       */
      public Builder setTelefoneBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        telefone_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Contato)
    }

    // @@protoc_insertion_point(class_scope:Contato)
    private static final AgendaOuterClass.Contato DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new AgendaOuterClass.Contato();
    }

    public static AgendaOuterClass.Contato getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Contato>
        PARSER = new com.google.protobuf.AbstractParser<Contato>() {
      public Contato parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Contato(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Contato> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Contato> getParserForType() {
      return PARSER;
    }

    public AgendaOuterClass.Contato getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Contato_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Contato_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Agenda.proto\")\n\007Contato\022\014\n\004nome\030\001 \002(\t\022" +
      "\020\n\010telefone\030\002 \002(\t2o\n\006Agenda\022!\n\tAdicionar" +
      "\022\010.Contato\032\010.Contato\"\000\022\037\n\007Remover\022\010.Cont" +
      "ato\032\010.Contato\"\000\022!\n\tConsultar\022\010.Contato\032\010" +
      ".Contato\"\000"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Contato_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Contato_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Contato_descriptor,
        new java.lang.String[] { "Nome", "Telefone", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
