# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import Agenda_pb2 as Agenda__pb2


class AgendaStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Adicionar = channel.unary_unary(
        '/Agenda/Adicionar',
        request_serializer=Agenda__pb2.Contato.SerializeToString,
        response_deserializer=Agenda__pb2.Contato.FromString,
        )
    self.Remover = channel.unary_unary(
        '/Agenda/Remover',
        request_serializer=Agenda__pb2.Contato.SerializeToString,
        response_deserializer=Agenda__pb2.Contato.FromString,
        )
    self.Consultar = channel.unary_unary(
        '/Agenda/Consultar',
        request_serializer=Agenda__pb2.Contato.SerializeToString,
        response_deserializer=Agenda__pb2.Contato.FromString,
        )


class AgendaServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Adicionar(self, request, context):
    """o servidor vai ler do cliente na 'stream' passada por parametro
    CLIENT SIDE
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Remover(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Consultar(self, request, context):
    """o cliente vai escrever e aguardar a resposta no 'stream' do return do server
    SERVER SIDE
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AgendaServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Adicionar': grpc.unary_unary_rpc_method_handler(
          servicer.Adicionar,
          request_deserializer=Agenda__pb2.Contato.FromString,
          response_serializer=Agenda__pb2.Contato.SerializeToString,
      ),
      'Remover': grpc.unary_unary_rpc_method_handler(
          servicer.Remover,
          request_deserializer=Agenda__pb2.Contato.FromString,
          response_serializer=Agenda__pb2.Contato.SerializeToString,
      ),
      'Consultar': grpc.unary_unary_rpc_method_handler(
          servicer.Consultar,
          request_deserializer=Agenda__pb2.Contato.FromString,
          response_serializer=Agenda__pb2.Contato.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Agenda', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
