# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import MemoryGame_pb2 as MemoryGame__pb2


class MemoryGameStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Jogar = channel.unary_unary(
        '/MemoryGame/Jogar',
        request_serializer=MemoryGame__pb2.Id.SerializeToString,
        response_deserializer=MemoryGame__pb2.Endereco.FromString,
        )
    self.Assistir = channel.unary_unary(
        '/MemoryGame/Assistir',
        request_serializer=MemoryGame__pb2.Id.SerializeToString,
        response_deserializer=MemoryGame__pb2.Endereco.FromString,
        )
    self.FimJogo = channel.unary_unary(
        '/MemoryGame/FimJogo',
        request_serializer=MemoryGame__pb2.Id.SerializeToString,
        response_deserializer=MemoryGame__pb2.Id.FromString,
        )


class MemoryGameServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Jogar(self, request, context):
    """O servidor ira retornar um endereco
    este endereco eh o endereco de multcastSocket onde os clientes de um grupo estao jogando

    quando for iniciar um jogo
    o id nao eh usado para nada
    mas o protobuf requer algo como parametro
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Assistir(self, request, context):
    """envia o id que quer assistir e recebe o endereco
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FimJogo(self, request, context):
    """quando acabar o jogo, avisa o servidor
    o Id retorno nao servira para nada
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MemoryGameServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Jogar': grpc.unary_unary_rpc_method_handler(
          servicer.Jogar,
          request_deserializer=MemoryGame__pb2.Id.FromString,
          response_serializer=MemoryGame__pb2.Endereco.SerializeToString,
      ),
      'Assistir': grpc.unary_unary_rpc_method_handler(
          servicer.Assistir,
          request_deserializer=MemoryGame__pb2.Id.FromString,
          response_serializer=MemoryGame__pb2.Endereco.SerializeToString,
      ),
      'FimJogo': grpc.unary_unary_rpc_method_handler(
          servicer.FimJogo,
          request_deserializer=MemoryGame__pb2.Id.FromString,
          response_serializer=MemoryGame__pb2.Id.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'MemoryGame', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
